import './state.js';
globalThis.EMOJI_CATEGORIES = {
    'smileys': {
        icon: '😀',
        title: 'Smileys',
        list: [
            { char: '😀', tags: 'smiley smile happy grin face' },{ char: '😃', tags: 'smiley smile happy grin face' },{ char: '😄', tags: 'smiley smile happy grin face' },{ char: '😁', tags: 'smiley smile happy grin face' },{ char: '😆', tags: 'smiley smile happy grin face' },{ char: '😅', tags: 'smiley smile happy grin sweat face' },{ char: '🤣', tags: 'smiley laugh rofl face' },{ char: '😂', tags: 'smiley laugh tear face' },{ char: '🙂', tags: 'smiley smile face' },{ char: '🙃', tags: 'smiley upside down face' },{ char: '😉', tags: 'smiley wink face' },{ char: '😊', tags: 'smiley smile blush face' },{ char: '😇', tags: 'smiley angel halo face' },{ char: '🥰', tags: 'smiley love hearts blush face' },{ char: '😍', tags: 'smiley love hearts eyes face' },{ char: '🤩', tags: 'smiley star eyes face' },{ char: '😘', tags: 'smiley love kiss face' },{ char: '😋', tags: 'smiley yum delicious face' },{ char: '😛', tags: 'smiley tongue face' },{ char: '😜', tags: 'smiley tongue wink face' },{ char: '🤪', tags: 'smiley crazy tongue face' },{ char: '🤑', tags: 'smiley money mouth face' },{ char: '😎', tags: 'smiley cool sunglasses face' },{ char: '🤓', tags: 'smiley nerd glasses face' },{ char: '🧐', tags: 'smiley monocle face' },{ char: '🤔', tags: 'smiley think face' },{ char: '😐', tags: 'smiley neutral face' },{ char: '😑', tags: 'smiley expressionless face' },{ char: '😏', tags: 'smiley smirk face' },{ char: '😒', tags: 'smiley unamused face' },{ char: '😬', tags: 'smiley grimace face' },{ char: '🤥', tags: 'smiley lie liar face' },{ char: '😌', tags: 'smiley relieved face' },{ char: '😔', tags: 'smiley pensive face' },{ char: '😪', tags: 'smiley sleepy tear face' },{ char: '😴', tags: 'smiley sleep face' },{ char: '😷', tags: 'smiley mask sick face' },{ char: '🤢', tags: 'smiley nauseous green face' },{ char: '🤮', tags: 'smiley vomit face' },{ char: '🥵', tags: 'smiley hot red sweat face' },{ char: '🥶', tags: 'smiley cold blue ice face' },{ char: '😵', tags: 'smiley dizzy face' },{ char: '🤯', tags: 'smiley mind blown explode head face' },{ char: '🥳', tags: 'smiley party celebrate face' },{ char: '💀', tags: 'skull dead bones' },{ char: '💩', tags: 'poop dump' },{ char: '🔥', tags: 'fire hot lit burn' },{ char: '✨', tags: 'sparkles gold shine magic' },{ char: '🌟', tags: 'star gold glow' },{ char: '⭐', tags: 'star gold' },{ char: '❤️', tags: 'love heart red' },{ char: '💖', tags: 'love heart sparkles' },{ char: '💔', tags: 'heart broken' }
        ]
    },
    'animals': {
        icon: '🐶',
        title: 'Nature',
        list: [
            { char: '🐶', tags: 'dog puppy animal pet' },{ char: '🐱', tags: 'cat kitty animal pet' },{ char: '🐭', tags: 'mouse animal' },{ char: '🐰', tags: 'rabbit bunny animal' },{ char: '🦊', tags: 'fox animal' },{ char: '🐻', tags: 'bear animal' },{ char: '🐼', tags: 'panda animal' },{ char: '🐨', tags: 'koala animal' },{ char: '🐯', tags: 'tiger animal' },{ char: '🦁', tags: 'lion animal' },{ char: '🐮', tags: 'cow animal' },{ char: '🐷', tags: 'pig animal' },{ char: '🐸', tags: 'frog animal' },{ char: '🐵', tags: 'monkey animal' },{ char: '🐒', tags: 'monkey animal' },{ char: '🐧', tags: 'penguin animal' },{ char: '🐦', tags: 'bird animal' },{ char: '🦆', tags: 'duck animal' },{ char: '🦅', tags: 'eagle animal' },{ char: '🦉', tags: 'owl animal' },{ char: '🐺', tags: 'wolf animal' },{ char: '🦄', tags: 'unicorn animal magic' },{ char: '🐝', tags: 'bee insect' },{ char: '🐛', tags: 'bug caterpillar insect' },{ char: '🦋', tags: 'butterfly insect' },{ char: '🕷️', tags: 'spider insect' },{ char: '🐢', tags: 'turtle animal' },{ char: '🐍', tags: 'snake animal' },{ char: '🐙', tags: 'octopus ocean sea' },{ char: '🐬', tags: 'dolphin ocean sea' },{ char: '🐳', tags: 'whale ocean sea' },{ char: '🦈', tags: 'shark ocean sea' },{ char: '🌲', tags: 'tree forest pine green' },{ char: '🌵', tags: 'cactus desert green' },{ char: '🍀', tags: 'clover leaf green luck' },{ char: '🍁', tags: 'maple leaf red fall' },{ char: '🌸', tags: 'flower blossom pink spring' },{ char: '🌹', tags: 'rose flower red love' },{ char: '🌻', tags: 'sunflower flower yellow' }
        ]
    },
    'food': {
        icon: '🍔',
        title: 'Food & Drink',
        list: [
            { char: '🍏', tags: 'apple green fruit food' },{ char: '🍎', tags: 'apple red fruit food' },{ char: '🍊', tags: 'orange fruit food' },{ char: '🍌', tags: 'banana fruit food' },{ char: '🍉', tags: 'watermelon fruit food' },{ char: '🍇', tags: 'grape fruit food' },{ char: '🍓', tags: 'strawberry fruit food' },{ char: '🍒', tags: 'cherry fruit food' },{ char: '🍑', tags: 'peach fruit food' },{ char: '🍍', tags: 'pineapple fruit food' },{ char: '🥥', tags: 'coconut fruit food' },{ char: '🥝', tags: 'kiwi fruit food' },{ char: '🍅', tags: 'tomato vegetable food' },{ char: '🍆', tags: 'eggplant aubergine vegetable food' },{ char: '🥑', tags: 'avocado vegetable food' },{ char: '🌽', tags: 'corn vegetable food' },{ char: '🥕', tags: 'carrot vegetable food' },{ char: '🥔', tags: 'potato vegetable food' },{ char: '🥐', tags: 'croissant bread bakery food' },{ char: '🍞', tags: 'bread toast bakery food' },{ char: '🥓', tags: 'bacon meat food' },{ char: '🥩', tags: 'steak meat food' },{ char: '🍔', tags: 'hamburger burger fastfood food' },{ char: '🍕', tags: 'pizza fastfood food' },{ char: '🌭', tags: 'hotdog fastfood food' },{ char: '🍟', tags: 'fries fastfood food' },{ char: '🥚', tags: 'egg food' },{ char: '🍿', tags: 'popcorn movie snack food' },{ char: '🥟', tags: 'dumpling dimsum food' },{ char: '🍣', tags: 'sushi japanese food' },{ char: '🍷', tags: 'wine glass drink alcohol' },{ char: '🍺', tags: 'beer mug drink alcohol' },{ char: '🍻', tags: 'beers cheers drink alcohol' },{ char: '☕', tags: 'coffee cafe mug drink hot' },{ char: '🍵', tags: 'tea green cup drink hot' }
        ]
    },
    'activities': {
        icon: '⚽',
        title: 'Activities',
        list: [
            { char: '⚽', tags: 'soccer football ball sports' },{ char: '🏀', tags: 'basketball ball sports' },{ char: '🏈', tags: 'football ball sports' },{ char: '⚾', tags: 'baseball ball sports' },{ char: '🥎', tags: 'softball ball sports' },{ char: '🎾', tags: 'tennis ball sports' },{ char: '🏐', tags: 'volleyball ball sports' },{ char: '🎱', tags: 'billiards pool ball sports' },{ char: '🏓', tags: 'pingpong table tennis ball sports' },{ char: '🏸', tags: 'badminton sports' },{ char: '🏹', tags: 'archery bow arrow sports' },{ char: '🎣', tags: 'fishing rod fish sports' },{ char: '🎯', tags: 'dart target bullseye' },{ char: '🪁', tags: 'kite fly' },{ char: '🎮', tags: 'controller game video sports console' },{ char: '🕹️', tags: 'joystick game video console' },{ char: '🎰', tags: 'slot machine game casino' },{ char: '🎲', tags: 'die dice game board' },{ char: '🧩', tags: 'puzzle piece game' },{ char: '🎨', tags: 'paint palette art design' },{ char: '🎬', tags: 'clapperboard movie cinema' },{ char: '🎤', tags: 'microphone singing music' },{ char: '🎧', tags: 'headphones music audio' },{ char: '🎹', tags: 'piano keyboard music instrument' },{ char: '🥁', tags: 'drum music instrument' },{ char: '🎸', tags: 'guitar music instrument' },{ char: '🎻', tags: 'violin music instrument' }
        ]
    },
    'travel': {
        icon: '🚗',
        title: 'Travel',
        list: [
            { char: '🚗', tags: 'car red automobile travel transport' },{ char: '🚕', tags: 'taxi cab yellow travel transport' },{ char: '🚓', tags: 'police car travel transport' },{ char: '🚒', tags: 'fire engine truck travel transport' },{ char: '🚐', tags: 'van travel transport' },{ char: '🚚', tags: 'truck transport' },{ char: '🚜', tags: 'tractor transport farm' },{ char: '🛵', tags: 'scooter transport' },{ char: '🏍️', tags: 'motorcycle bike transport' },{ char: '🚨', tags: 'police siren emergency light' },{ char: '🚲', tags: 'bicycle bike transport sports' },{ char: '⛽', tags: 'gas fuel station' },{ char: '⚓', tags: 'anchor ship boat navy' },{ char: '⛵', tags: 'sailboat ship boat travel' },{ char: '🛶', tags: 'canoe kayak boat travel' },{ char: '✈️', tags: 'airplane plane flight travel' },{ char: '🚀', tags: 'rocket space launch work speed' },{ char: '🚁', tags: 'helicopter travel flight' },{ char: '🏕️', tags: 'camping outdoor travel' },{ char: '🏠', tags: 'house home building' },{ char: '🏡', tags: 'house garden home building' },{ char: '🏢', tags: 'office business building' },{ char: '🏥', tags: 'hospital medical building' },{ char: '🏫', tags: 'school education building' },{ char: '🏭', tags: 'factory building industry' },{ char: '🏰', tags: 'castle fortress building' },{ char: '⛩️', tags: 'shrine torii gate Japanese' },{ char: '⛲', tags: 'fountain park' },{ char: '🌌', tags: 'milkyway galaxy space night' },{ char: '🌉', tags: 'bridge night' }
        ]
    },
    'objects': {
        icon: '💡',
        title: 'Objects',
        list: [
            { char: '⌚', tags: 'watch time clock' },{ char: '📱', tags: 'phone mobile smartphone cell' },{ char: '💻', tags: 'laptop computer tech' },{ char: '⌨️', tags: 'keyboard tech computer' },{ char: '🖥️', tags: 'monitor screen computer' },{ char: '🖨️', tags: 'printer office paper' },{ char: '📸', tags: 'camera photo picture' },{ char: '🎥', tags: 'camera movie video' },{ char: '☎️', tags: 'telephone phone landline' },{ char: '📺', tags: 'tv television screen' },{ char: '📻', tags: 'radio music audio' },{ char: '🎙️', tags: 'microphone studio recording' },{ char: '🧭', tags: 'compass direction travel' },{ char: '⏰', tags: 'alarm clock time' },{ char: '⏳', tags: 'hourglass time sand' },{ char: '🔋', tags: 'battery power energy charge' },{ char: '💡', tags: 'lightbulb idea light bulb' },{ char: '🔦', tags: 'flashlight torch light' },{ char: '🕯️', tags: 'candle light wax' },{ char: '🧯', tags: 'extinguisher safety fire' },{ char: '💵', tags: 'dollar cash money green' },{ char: '🪙', tags: 'coin gold money cash' },{ char: '💰', tags: 'money bag gold cash' },{ char: '💳', tags: 'credit card money bank' },{ char: '💎', tags: 'gem diamond jewel' },{ char: '⚖️', tags: 'scales justice balance' },{ char: '🔨', tags: 'hammer tool construction' },{ char: '🔧', tags: 'wrench spanner tool fix' },{ char: '🔩', tags: 'bolt nut screw tool hardware' },{ char: '⚙️', tags: 'gear settings tool mechanics' },{ char: '🔐', tags: 'lock key secure private' },{ char: '🔒', tags: 'lock secure private' },{ char: '🔓', tags: 'lock open insecure' },{ char: '🔑', tags: 'key lock open' },{ char: '📚', tags: 'books study read education' },{ char: '📝', tags: 'pencil paper write memo note' },{ char: '📌', tags: 'pushpin pin map post' },{ char: '✉️', tags: 'envelope mail letter' },{ char: '🔔', tags: 'bell notification alert' }
        ]
    },
    'flags': {
        icon: '🚩',
        title: 'Flags',
        list: [
            { char: '🏁', tags: 'flag checkered finish race' },{ char: '🚩', tags: 'flag red post' },{ char: '🎌', tags: 'flags crossed Japan festival' },{ char: '🏴', tags: 'flag black' },{ char: '🏳️', tags: 'flag white peace surrender' },{ char: '🏳️‍🌈', tags: 'flag rainbow pride lgbt' },{ char: '🏳️‍⚧️', tags: 'flag transgender pride lgbt' },{ char: '🏴‍☠️', tags: 'flag pirate skull crossbones' }
        ]
    }
};
