import './icons.js';
import './router.js';
import './dom.js';
import './api.js';
import './editor.js';
import './format.js';
import './markdown.js';
import './sse.js';
import './sse-events.js';
import './chat.js';
import './chat-history.js';
import './chat-stream.js';
import './layout.js';
import './scroll-sync.js';
import './preview.js';
import './models.js';
import './search.js';
import './files.js';
import './status.js';
import './panels.js';
import './tree.js';
import './tree-actions.js';
import './notes.js';
import './emoji-data.js';
import './emoji.js';
import './settings.js';
import './editor-modes.js';
import './responsive.js';
import './palette.js';
import './row-menu.js';
import './keyboard.js';
import './bootstrap.js';
import { initActions } from './actions.js';
import { initResponsive } from './responsive.js';
import { initPalette } from './palette.js';
import { initRowMenu } from './row-menu.js';
import { initKeyboard } from './keyboard.js';
import { hydrateIcons } from './icons.js';
import { decodeHtml } from './dom.js';

globalThis.decodeHtml = decodeHtml;
hydrateIcons(document);
initActions();
initResponsive();
initPalette();
// After initActions, so a row-menu item's command runs before the menu closes.
initRowMenu();
initKeyboard();
document.addEventListener('rune:render-preview', () => renderPreview());
